export const todo_data = [
  {
    todo_id: 1,
    title: "Complete React Project",
    body: "Finish the coding and testing for the React project.",
    due_date: "2023-12-31T23:59:59",
    status: "in_progress",
    priority: "High",
  },
  {
    todo_id: 2,
    title: "Chess Tournament Preparation",
    body: "Practice chess strategies for the upcoming tournament.",
    due_date: "2023-12-15T18:00:00",
    status: "open",
    priority: "Medium",
  },
  {
    todo_id: 3,
    title: "Gym Workout",
    body: "Hit the gym for a strength training session.",
    due_date: "2023-12-14T08:00:00",
    status: "completed",
    priority: "Medium",
  },
  {
    todo_id: 4,
    title: "Anime Marathon",
    body: "Watch the latest episodes of favorite anime series.",
    due_date: "2023-12-20T20:00:00",
    status: "open",
    priority: "Low",
  },
  {
    todo_id: 5,
    title: "Photography Expedition",
    body: "Capture stunning photos during a photography trip.",
    due_date: "2023-12-25T12:00:00",
    status: "open",
    priority: "Low",
  },
  {
    todo_id: 6,
    title: "Node.js Project Enhancement",
    body: "Improve features and performance of a Node.js project.",
    due_date: "2023-12-30T16:30:00",
    status: "in_progress",
    priority: "Medium",
  },
  {
    todo_id: 7,
    title: "Game Night with Friends",
    body: "Plan and organize a gaming night with friends.",
    due_date: "2023-12-18T19:00:00",
    status: "open",
    priority: "Low",
  },
  {
    todo_id: 8,
    title: "Redux State Management Tutorial",
    body: "Create a tutorial on effective Redux state management.",
    due_date: "2023-12-28T14:00:00",
    status: "open",
    priority: "Medium",
  },
  {
    todo_id: 9,
    title: "Database Optimization for Rails App",
    body: "Optimize database queries for a Ruby on Rails application.",
    due_date: "2023-12-22T10:00:00",
    status: "in_progress",
    priority: "Medium",
  },
  {
    todo_id: 10,
    title: "Study TypeScript Best Practices",
    body: "Read and implement best practices for TypeScript development.",
    due_date: "2023-12-17T15:30:00",
    status: "open",
    priority: "Low",
  },
];

export type Todo = (typeof todo_data)[0];
